export const LOGIN_REQUEST='LOGIN_REQUEST';
export const LOGIN_SUCCESS='LOGIN_SUCCESS';
export const LOGIN_FAILURE='LOGIN_FAILURE';

export const SALE_NORMAL='SALE_NORMAL';
export const SALE_RETURN='SALE_RETURN';
export const SALE_MODAL_CHANGE="SALE_MODAL_CHANGE";

export const ITEM_CHANGE='ITEM_CHANGE';
export const ITEM_SET_LOADING='ITEM_SET_LOADING';

export const SALERESULT_CHANGE='SALERESULT_CHANGE';

export const ORDER_SAVE_SUCCESS='ORDER_SAVE_SUCCESS';
export const ORDER_SAVE_REQUEST='ORDER_SAVE_REQUEST';
export const ORDER_SAVE_ERROR='ORDER_SAVE_ERROR';

export const SALESMAN_CHANGE='SALESMAN_CHANGE';

export const SALEPAYMENT_CHANGE='SALEPAYMENT_CHANGE';
export const SALEPAY_CHANGE='SALEPAY_CHANGE';

export const CUSTOMER_CHANGE='CUSTOMER_CHANGE';
export const CUSTOMER_REQUEST='CUSTOMER_REQUEST';
export const CUSTOMER_ERROR='CUSTOMER_ERROR';
export const CUSTOMER_INIT='CUSTOMER_INIT';

export const COUPON_REQUEST='COUPON_REQUEST';
export const COUPON_SUCCESS='COUPON_SUCCESS';
export const COUPON_FAILURE='COUPON_FAILURE';
export const COUPON_SET="COUPON_SET";
export const COUPON_INIT="COUPON_INIT";